import { ReadmeProject, ReadmeBackup, ReadmeHistoryLog, ReadmePreferences } from '../types';
import { isValidHttpUrl } from './readmeUtils';

export const ESTIMATED_MAX_CHARS = 4500000; // ~4.5MB

type UnknownRecord = Record<string, unknown>;

function isRecord(value: unknown): value is UnknownRecord {
  return typeof value === 'object' && value !== null;
}

function cleanText(value: unknown): string {
  return typeof value === 'string' ? value.replace(/<\/?[^>]+(>|$)/g, "") : '';
}

/**
 * Validates protocol and XSS risks in URLs, stripping html tags
 */
export function sanitizeUrl(url?: unknown): string {
  if (typeof url !== 'string') return '';
  const trimmed = url.trim().replace(/<\/?[^>]+(>|$)/g, "");
  return isValidHttpUrl(trimmed) ? trimmed : '';
}

function isDataImageSource(source?: unknown): source is string {
  return typeof source === 'string' && source.startsWith('data:image/');
}

/**
 * Recursively deep-sanitizes a project structure to protect against any unsafe injection, HTML, or malformed data
 */
export function sanitizeProject(project: unknown): ReadmeProject {
  const source = isRecord(project) ? project : {};
  const optionalSections = isRecord(source.optionalSections) ? source.optionalSections : {};

  const cleanOptional = {
    prerequisites: !!optionalSections.prerequisites,
    scripts: !!optionalSections.scripts,
    folderStructure: !!optionalSections.folderStructure,
    roadmap: !!optionalSections.roadmap,
    contributing: !!optionalSections.contributing,
    authors: !!optionalSections.authors,
    acknowledgements: !!optionalSections.acknowledgements,
    contact: !!optionalSections.contact,
    tests: !!optionalSections.tests
  };

  return {
    id: typeof source.id === 'string' ? source.id : Math.random().toString(36).substring(2, 9),
    name: cleanText(source.name),
    description: cleanText(source.description),
    technologies: Array.isArray(source.technologies) ? source.technologies.map(cleanText) : [],
    features: Array.isArray(source.features) ? source.features.map(cleanText) : [],
    installation: typeof source.installation === 'string' ? source.installation : '',
    usage: typeof source.usage === 'string' ? source.usage : '',
    license: typeof source.license === 'string' ? source.license : '',
    customLicense: typeof source.customLicense === 'string' ? source.customLicense : '',
    repositoryUrl: sanitizeUrl(source.repositoryUrl),
    deployUrl: sanitizeUrl(source.deployUrl),
    websiteUrl: sanitizeUrl(source.websiteUrl),
    authorName: cleanText(source.authorName),
    authorEmail: cleanText(source.authorEmail),
    authorUrl: sanitizeUrl(source.authorUrl),
    linkedinUrl: sanitizeUrl(source.linkedinUrl),
    screenshots: Array.isArray(source.screenshots) ? source.screenshots.map((item) => {
      const screenshot = isRecord(item) ? item : {};
      return {
      id: typeof screenshot.id === 'string' ? screenshot.id : Math.random().toString(36).substring(2, 9),
      source: isDataImageSource(screenshot.source) ? screenshot.source : sanitizeUrl(screenshot.source),
      alt: cleanText(screenshot.alt) || 'Screenshot',
      caption: cleanText(screenshot.caption)
      };
    }) : [],
    optionalSections: cleanOptional,
    prerequisitesContent: typeof source.prerequisitesContent === 'string' ? source.prerequisitesContent : '',
    scriptsContent: typeof source.scriptsContent === 'string' ? source.scriptsContent : '',
    folderStructureContent: typeof source.folderStructureContent === 'string' ? source.folderStructureContent : '',
    roadmapContent: typeof source.roadmapContent === 'string' ? source.roadmapContent : '',
    contributingContent: typeof source.contributingContent === 'string' ? source.contributingContent : '',
    authorsContent: typeof source.authorsContent === 'string' ? source.authorsContent : '',
    acknowledgementsContent: typeof source.acknowledgementsContent === 'string' ? source.acknowledgementsContent : '',
    contactContent: typeof source.contactContent === 'string' ? source.contactContent : '',
    testsContent: typeof source.testsContent === 'string' ? source.testsContent : '',
    createdAt: typeof source.createdAt === 'string' ? source.createdAt : new Date().toISOString(),
    updatedAt: typeof source.updatedAt === 'string' ? source.updatedAt : new Date().toISOString()
  };
}

/**
 * Validates the parsed JSON backup structure to ensure it is generated by README
 */
export function validateBackup(data: unknown): data is ReadmeBackup {
  if (!isRecord(data)) return false;
  if (data.appName !== 'README') return false;
  if (data.schemaVersion !== 1) return false;
  if (!Array.isArray(data.projects)) return false;
  if (data.activeProject !== null && data.activeProject !== undefined && typeof data.activeProject !== 'object') return false;
  if (data.history !== undefined && !Array.isArray(data.history)) return false;
  if (data.preferences !== undefined && (typeof data.preferences !== 'object' || data.preferences === null)) return false;
  
  // Validate basic types for projects
  const ids = new Set<string>();
  for (const p of data.projects) {
    if (!isRecord(p) || typeof p.id !== 'string') {
      return false;
    }
    if (ids.has(p.id)) return false;
    ids.add(p.id);
  }
  
  return true;
}

/**
 * Estimates if the merged/substituted data size fits within safe browser limits (~4.5MB)
 */
export function isBackupTooLarge(
  projects: unknown[],
  activeProject: unknown,
  preferences: unknown,
  history: unknown[]
): boolean {
  const serialized = JSON.stringify(projects) + 
                     JSON.stringify(activeProject) + 
                     JSON.stringify(preferences) + 
                     JSON.stringify(history);
  return serialized.length > ESTIMATED_MAX_CHARS;
}
